name: Metrics

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Overview
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TiboTsr
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          filename: assets/metrics-overview.svg

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TiboTsr
          template: classic
          base: ""
          config_timezone: Europe/Paris
          filename: assets/metrics-languages.svg
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6

      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TiboTsr
          template: classic
          base: ""
          config_timezone: Europe/Paris
          filename: assets/metrics-wakatime.svg
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, editors, os
          plugin_wakatime_limit: 6
